---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: ${storageclass}
    app: jenkins
    role: jenkins-data
  name: jenkins-pv
  namespace: jenkins
spec:
  capacity:
    storage: 2500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ${storageclass}
  local:
    path: /datadrive/jenkins-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "${selectorkey}"
          operator: In
          values:
          - "${selectorvalue}"
  persistentVolumeReclaimPolicy: Retain
